name: trigger
on:
  push: 
    branches: [master]
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -s -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/arkency/sites/dispatches \
            -d "{\"event_type\": \"trigger\" }"
